gitSafeReplacementChar: '-'
branchName: '${issue.number}-${issue.title}'
silent: true
defaultBranch: 'dev'
branches:
  - label: enhancement
    prefix: feature/
    name: dev
    skip: false
  - label: bug
    name: staging
    prefix: bug/
    skip: false
  - label: '*'
    skip: true
