name: Upload My Demo App monthly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 */30 * *'

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

jobs:
  download_upload_app:
    runs-on: ubuntu-latest
    steps:
      - name: Download My Demo App apk
        uses: wei/curl@v1.1.1
        with:
          args: -L -o Android-MyDemoAppRN.apk https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/Android-MyDemoAppRN.1.3.0.build-244.apk
      - name: Upload My Demo App apk
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"Android-MyDemoAppRN.apk"' --form 'name="Android-MyDemoAppRN.apk"'
      - name: Download My Demo App zip
        uses: wei/curl@v1.1.1
        with:
          args: -L -o iOS-Simulator-MyRNDemoApp.zip https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/iOS-Simulator-MyRNDemoApp.1.3.0-162.zip
      - name: Upload My Demo App zip
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"iOS-Simulator-MyRNDemoApp.zip"' --form 'name="iOS-Simulator-MyRNDemoApp.zip"'
      - name: Download My Demo App ipa
        uses: wei/curl@v1.1.1
        with:
          args: -L -o iOS-Real-Device-MyRNDemoApp.ipa https://github.com/saucelabs/my-demo-app-rn/releases/download/v1.3.0/iOS-Real-Device-MyRNDemoApp.1.3.0-162.ipa
      - name: Upload My Demo App ipa
        uses: wei/curl@v1.1.1
        with:
          args: -u "$SAUCE_USERNAME:$SAUCE_ACCESS_KEY" --location --request POST 'https://api.eu-central-1.saucelabs.com/v1/storage/upload' --form 'payload=@"iOS-Real-Device-MyRNDemoApp.ipa"' --form 'name="iOS-Real-Device-MyRNDemoApp.ipa"'